export const animal = {
	id: 1,
	name: 'Bobby',
	description: 'A very good friend',
	birthdate: '2020-01-01',
	catsFriendly: true,
	dogsFriendly: true,
	childrenFriendly: true,
	ageRange: 3,
	behavioralComment: 'Very friendly and playful',
	sterilized: true,
	deceased: false,
	species: 1,
	breed: 'Golden Retriever',
	status: 2,
	icad: '123456789123458',
	gender: 2,
	size: 1,
	color: 'Golden',
	coat: 'Long',
};

export const animals = [
	{
		id: 1,
		name: 'Bobby',
		description: 'A very good friend',
		birthdate: '2020-01-01',
		catsFriendly: true,
		dogsFriendly: true,
		childrenFriendly: true,
		ageRange: 3,
		behavioralComment: 'Very friendly and playful',
		sterilized: true,
		deceased: false,
		species: 2,
		breed: 'Golden Retriever',
		status: 1,
		icad: '123456789123458',
		gender: 1,
		size: 3,
		color: 'Golden',
		coat: 'Long',
	},
	{
		id: 2,
		name: 'Spike',
		description: 'He loves to play',
		birthdate: '2018-04-28',
		catsFriendly: false,
		dogsFriendly: true,
		childrenFriendly: true,
		ageRange: 3,
		behavioralComment: "Very friendly and playful, don't like cats",
		sterilized: true,
		deceased: false,
		species: 2,
		breed: 'Labrador',
		status: 3,
		icad: '254789654123584',
		gender: 1,
		size: 3,
		color: 'Black',
		coat: 'Short',
	},
	{
		id: 3,
		name: 'Puffy',
		description: 'A very good friend',
		birthdate: '2019-02-15',
		catsFriendly: true,
		dogsFriendly: true,
		childrenFriendly: true,
		ageRange: 4,
		behavioralComment: 'Very friendly and playful',
		sterilized: true,
		deceased: false,
		species: 1,
		breed: 'Persian',
		status: 3,
		icad: '123456789123458',
		gender: 2,
		size: 2,
		color: 'White',
		coat: 'Long',
	},
];
