# Utiliser une image Node officielle comme image de base
FROM node:lts-alpine

# Définir le répertoire de travail dans le conteneur
WORKDIR /app

# Copier les fichiers 'package.json' et 'package-lock.json' (si disponible)
COPY package*.json ./

# Installer les dépendances du projet
RUN npm install

# Copier les fichiers et dossiers du projet dans le répertoire de travail (/app)
COPY . .

# Exposer le port sur lequel l'application va tourner
EXPOSE 5173

# Commande pour démarrer l'application en mode développement
# CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "5173"]
