version: '3.8'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: vue_frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
    command: > 
      sh -c "npm install && npm run dev -- --host 0.0.0.0 --port 5173"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      
    container_name: laravel_backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    volumes:
      - './backend:/var/www/html'
    networks:
      - osecours
    depends_on:
      - postgres
    command: "php artisan serve --host=0.0.0.0 --port=8000"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8083:8080"
    networks:
      - osecours

  postgres:    
    image: postgres:latest  
    env_file:
      - ./.env
    environment:
      POSTGRES_DB: '${DB_DATABASE}'
      POSTGRES_USER: '${DB_USERNAME}'
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
    ports:
      - "5432:5432"
    volumes:
      - osecours-postgres:/var/lib/postgresql/data
    networks:
      - osecours

networks:
  osecours:
    driver: bridge

volumes:
  osecours-postgres:
    driver: local
