version: '3.8'
services:
  
  frontend:
    build: ./frontend
    container_name: vue_frontend
    ports:
      - "8080:80"
    command: /bin/sh -c "echo 'Now API backend can be reached on port http://localhost:5555 and front end on port http://localhost:8080' && nginx -g 'daemon off;'"
volumes:
  db_data:
