openapi: 3.0.0
info:
  title: /api/users
  version: '1.0'
paths:
  /api/animals/all:
    get:
      operationId: e44043509ac374051a465bc4cf060028
      responses:
        '200':
          description: AOK
        '401':
          description: 'Not allowed'
