openapi: 3.0.0
info:
  title: "O'Secours"
  description: 'API pour gérer des ressources'
  version: '1.0'
servers:
  -
    url: 'http://localhost:8000/api'
    description: 'API Server'
paths:
  /animals/all:
    get:
      operationId: c7546f9cd96a5e416aca6b2c734067a4
      responses:
        '200':
          description: 'get list of all animals'
      security:
        -
          bearerAuth: []
  /animals:
    post:
      summary: 'register new animal'
      operationId: c503fd8d2a3ab739b0b33ca257cbba33
      requestBody:
        description: 'Animal fields'
        required: true
        content:
          application/json:
            schema:
              required:
                - specie_id
              properties:
                name:
                  type: string
                  maxLength: 100
                  example: Pupuce
                description:
                  type: string
                  example: 'Really cute'
                birth_date:
                  type: string
                  format: '1995-04-01'
                  example: Pupuce
                cats_friendly:
                  type: boolean
                  example: true
                dogs_friendly:
                  type: boolean
                  example: true
                children_friendly:
                  type: boolean
                  example: true
                age:
                  type: integer
                  example: 4
                behavioral_comment:
                  type: string
                  example: 'Love cuddle'
                sterilized:
                  type: boolean
                  example: true
                deceased:
                  type: boolean
                  example: false
                specie_id:
                  type: integer
                  example: 1
                gender_id:
                  type: integer
                  example: 2
                color_id:
                  type: integer
                  example: 3
                sizerange_id:
                  type: integer
                  example: 4
                agerange_id:
                  type: integer
                  example: 2
                breed_id:
                  type: integer
                  example: 2
                number:
                  type: string
                  maxLength: 15
                  example: 152A5P6
                email:
                  type: string
                  format: email
                  example: admin-lerefugedeschimeres@osecours.org
                password:
                  type: string
                  example: P@ssword_1
                association_id:
                  type: integer
                  example: 1
              type: object
      responses:
        '200':
          description: 'Utilisateur créé avec succès'
        '400':
          description: 'Requête invalide'
  /token/create:
    post:
      summary: 'Get token'
      operationId: 938115c0186bb008a47800d0efe0c8fe
      requestBody:
        description: 'create token for specific association'
        required: true
        content:
          application/json:
            schema:
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  format: email
                  example: admin-lerefugedeschimeres@osecours.org
                password:
                  type: string
                  example: P@ssword_1
                association_id:
                  type: integer
                  example: 1
              type: object
      responses:
        '200':
          description: 'Token created successfully'
        '401':
          description: Unauthorized
components:
  schemas:
    Address:
      title: Address
      description: 'Address model'
      properties:
        id:
          description: 'ID of the address'
          type: integer
          example: 1
        street1:
          description: 'First line of the street address'
          type: string
          example: '123 Main St'
        street2:
          description: 'Second line of the street address'
          type: string
          example: 'Apt 101'
        city_id:
          description: 'ID of the city'
          type: integer
          example: 1
      type: object
    Age_range:
      title: 'Age Range'
      description: 'Age Range model'
      properties:
        id:
          description: 'ID of the age range'
          type: integer
          example: 1
        name:
          description: 'Name of the age range'
          type: string
          example: Adult
        description:
          description: 'Description of the age range'
          type: string
          example: 'Between 3 to 7 years old'
      type: object
    Association:
      title: Association
      description: 'Association model'
      properties:
        id:
          description: 'ID of the association'
          type: integer
          example: 1
        name:
          description: 'Name of the association'
          type: string
          example: 'Animal Rescue Association'
        description:
          description: 'Description of the association'
          type: string
          example: 'A non-profit organization dedicated to rescuing animals'
        siret:
          description: 'SIRET number of the association'
          type: string
          maxLength: 14
          minLength: 14
          example: '12345678901234'
        rib:
          description: "RIB (Relevé d'Identité Bancaire) of the association"
          type: string
          maxLength: 34
          example: 'FRXX XXXX XXXX XXXX XXXX XXXX XXX'
      type: object
    Breed:
      title: Breed
      description: 'Breed model'
      properties:
        id:
          description: 'ID of the breed'
          type: integer
          example: 1
        name:
          description: 'Name of the breed'
          type: string
          example: 'Labrador Retriever'
        description:
          description: 'Description of the breed'
          type: string
          example: 'A medium-large gun dog breed known for its friendly and outgoing nature'
        specie_id:
          description: 'ID of the species to which the breed belongs'
          type: integer
          example: 1
      type: object
    City:
      title: City
      description: 'City model'
      properties:
        id:
          description: 'ID of the city'
          type: integer
          example: 1
        name:
          description: 'Name of the city'
          type: string
          example: 'New York'
        zipcode:
          description: 'Zip code of the city'
          type: string
          example: '10001'
      type: object
    Coat:
      title: Coat
      description: 'Coat model'
      properties:
        id:
          description: 'ID of the coat'
          type: integer
          example: 1
        name:
          description: 'Name of the coat'
          type: string
          example: Short
        description:
          description: 'Description of the coat'
          type: string
          example: 'A short-haired coat'
      type: object
    Color:
      title: Color
      description: 'Color model'
      properties:
        id:
          description: 'ID of the color'
          type: integer
          example: 1
        name:
          description: 'Name of the color'
          type: string
          example: Red
        description:
          description: 'Description of the color'
          type: string
          example: 'A vibrant red color'
        specie_id:
          description: 'ID of the species associated with this color'
          type: integer
          example: 1
      type: object
    Doctype:
      title: Doctype
      description: 'Document Type model'
      properties:
        id:
          description: 'ID of the document type'
          type: integer
          example: 1
        name:
          description: 'Name of the document type'
          type: string
          example: Passport
        description:
          description: 'Description of the document type'
          type: string
          example: 'A passport document'
      type: object
    Document:
      title: Document
      description: 'Document model'
      properties:
        id:
          description: 'ID of the document'
          type: integer
          example: 1
        filename:
          description: 'Name of the file'
          type: string
          example: document.pdf
        description:
          description: 'Description of the document'
          type: string
          example: 'A document describing the health status'
        size:
          description: 'Size of the document in bytes'
          type: integer
          example: 1024
        url:
          description: 'URL of the document'
          type: string
          example: 'http://example.com/document.pdf'
        date:
          description: 'Date of the document'
          type: string
          format: date
          example: '2024-04-16'
        mimetype_id:
          description: 'ID of the MIME type'
          type: integer
          example: 1
        doctype_id:
          description: 'ID of the document type'
          type: integer
          example: 1
      type: object
    Gender:
      title: Gender
      description: 'Gender model'
      properties:
        id:
          description: 'ID of the gender'
          type: integer
          example: 1
        name:
          description: 'Name of the gender'
          type: string
          example: Male
        description:
          description: 'Description of the gender'
          type: string
          example: 'Male gender'
      type: object
    Healthcare:
      title: Healthcare
      description: 'Healthcare model'
      properties:
        id:
          description: 'ID of the healthcare record'
          type: integer
          example: 1
        date:
          description: 'Date of the healthcare consultation'
          type: string
          format: date
          example: '2022-04-16'
        report:
          description: 'Report of the healthcare consultation'
          type: string
        weight:
          description: 'Weight of the animal during the healthcare consultation'
          type: number
          format: float
          example: 12.5
        size:
          description: 'Size of the animal during the healthcare consultation'
          type: number
          format: float
          example: 30.2
        animal_id:
          description: 'ID of the associated animal'
          type: integer
          example: 1
        document_id:
          description: 'ID of the associated document'
          type: integer
          example: 1
      type: object
    Identification:
      title: Identification
      description: 'Identification model'
      properties:
        id:
          description: 'ID of the identification record'
          type: integer
          example: 1
        date:
          description: 'Date of the identification'
          type: string
          format: date
          example: '2022-04-16'
        type:
          description: 'Type of identification (Chip or Tatoo)'
          type: string
          enum:
            - Chip
            - Tatoo
          example: Chip
        number:
          description: 'Identification number'
          type: string
          maxLength: 15
          minLength: 6
          example: '123456789'
        animal_id:
          description: 'ID of the associated animal'
          type: integer
          example: 1
      type: object
    Mimetype:
      title: Mimetype
      description: 'Mimetype model'
      properties:
        id:
          description: 'ID of the mimetype'
          type: integer
          example: 1
        name:
          description: 'Name of the mimetype'
          type: string
          example: application/pdf
      type: object
    Person:
      title: Person
      description: 'Person model'
      properties:
        id:
          description: 'ID of the person'
          type: integer
          example: 1
        created_at:
          description: 'Date and time when the person was created'
          type: string
          format: date-time
        updated_at:
          description: 'Date and time when the person was last updated'
          type: string
          format: date-time
        personable_type:
          description: 'Type of the associated entity (morphed)'
          type: string
        personable_id:
          description: 'ID of the associated entity (morphed)'
          type: integer
      type: object
    Role:
      title: Role
      description: 'Role model'
      properties:
        id:
          description: 'ID of the role'
          type: integer
          example: 1
        name:
          description: 'Name of the role'
          type: string
          example: admin
        created_at:
          description: 'Date and time when the role was created'
          type: string
          format: date-time
        updated_at:
          description: 'Date and time when the role was last updated'
          type: string
          format: date-time
      type: object
    Shelter:
      title: Shelter
      description: 'Shelter model'
      properties:
        id:
          description: 'ID of the shelter'
          type: integer
          example: 1
        name:
          description: 'Name of the shelter'
          type: string
          example: 'Animal Shelter'
        description:
          description: 'Description of the shelter'
          type: string
          example: 'A shelter for homeless animals'
        phone:
          description: 'Phone number of the shelter'
          type: string
          example: 123-456-7890
        email:
          description: 'Email address of the shelter'
          type: string
          example: info@example.com
        siret:
          description: 'SIRET number of the shelter'
          type: string
          maxLength: 14
          minLength: 14
          example: '12345678901234'
        created_at:
          description: 'Date and time when the shelter was created'
          type: string
          format: date-time
        updated_at:
          description: 'Date and time when the shelter was last updated'
          type: string
          format: date-time
      type: object
    Size_range:
      title: Size_range
      description: 'Size_range model'
      properties:
        id:
          description: 'ID of the size range'
          type: integer
          example: 1
        name:
          description: 'Name of the size range'
          type: string
          example: Small
        description:
          description: 'Description of the size range'
          type: string
          example: 'Small-sized animals'
        created_at:
          description: 'Date and time when the size range was created'
          type: string
          format: date-time
        updated_at:
          description: 'Date and time when the size range was last updated'
          type: string
          format: date-time
      type: object
    Specie:
      title: Specie
      description: 'Specie model'
      properties:
        id:
          description: 'ID of the specie'
          type: integer
          example: 1
        name:
          description: 'Name of the specie'
          type: string
          example: Cat
        description:
          description: 'Description of the specie'
          type: string
          example: 'Domestic cat'
        created_at:
          description: 'Date and time when the specie was created'
          type: string
          format: date-time
        updated_at:
          description: 'Date and time when the specie was last updated'
          type: string
          format: date-time
      type: object
    Status:
      title: Status
      description: 'Status model'
      properties:
        id:
          description: 'ID of the status'
          type: integer
          example: 1
        name:
          description: 'Name of the status'
          type: string
          example: Adopted
        description:
          description: 'Description of the status'
          type: string
          example: 'The animal has been adopted'
        created_at:
          description: 'Date and time when the status was created'
          type: string
          format: date-time
        updated_at:
          description: 'Date and time when the status was last updated'
          type: string
          format: date-time
      type: object
    User:
      title: User
      description: 'User model'
      properties:
        id:
          description: 'ID of the user'
          type: integer
          example: 1
        first_name:
          description: 'First name of the user'
          type: string
          example: John
        last_name:
          description: 'Last name of the user'
          type: string
          example: Doe
        phone:
          description: 'Phone number of the user'
          type: string
          example: '123456789'
        existing_cat_count:
          description: 'Number of existing cats owned by the user'
          type: integer
          example: 2
        existing_children_count:
          description: 'Number of existing children of the user'
          type: integer
          example: 1
        existing_dog_count:
          description: 'Number of existing dogs owned by the user'
          type: integer
          example: 0
        email:
          description: 'Email address of the user'
          type: string
          example: john@example.com
        created_at:
          description: 'Date and time when the user was created'
          type: string
          format: date-time
        updated_at:
          description: 'Date and time when the user was last updated'
          type: string
          format: date-time
      type: object
    Vaccine:
      title: Vaccine
      description: 'Vaccine model'
      properties:
        id:
          description: 'ID of the vaccine'
          type: integer
          example: 1
        name:
          description: 'Name of the vaccine'
          type: string
          example: Rabies
        description:
          description: 'Description of the vaccine'
          type: string
          example: 'Prevents rabies infection in animals'
        created_at:
          description: 'Date and time when the vaccine was created'
          type: string
          format: date-time
        updated_at:
          description: 'Date and time when the vaccine was last updated'
          type: string
          format: date-time
      type: object
  securitySchemes:
    bearerAuth:
      type: http
      description: 'JWT Authorization header using the Bearer scheme.'
      bearerFormat: JWT
      scheme: bearer
