name: Deploy Backend to Heroku

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to Heroku Container registry
      run: heroku container:login
      env:
        HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}}

    - name: Build Docker image
      run: docker build -t registry.heroku.com/osecours-api/web ./backend

    - name: Push and release Docker images
      run: |
        docker push registry.heroku.com/osecours-api/web
        heroku container:release web --app osecours-api
      env:
        HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}}
