name: Deploy backend to Heroku

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, pdo_mysql, dom, xml
          tools: composer:v2

      - name: Install dependencies
        run: |
          cd backend
          composer install --prefer-dist --no-progress --no-suggest

      - name: Run database migrations
        run: |
          cd backend
          php artisan migrate --force
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Unshallow the clone
        run: git fetch --all --unshallow

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12 # This action will deploy the app
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_API_NAME }} #Must be unique in Heroku
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          appdir: "backend"