name: Deploy to Heroku

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Heroku Container registry
      run: docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

    - name: Build and push Docker image
      run: |
        docker build -t registry.heroku.com/${{HEROKU_APP_API_NAME}}/web ./backend
        docker push registry.heroku.com/${{HEROKU_APP_API_NAME}}/web

    - name: Deploy to Heroku
      run: |
        heroku container:release web --app ${{HEROKU_APP_NAME}}
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_API_NAME }}