name: Deploy to Heroku

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      with:
        version: 26.1.0

    - name: Login to Heroku Container registry
      run: |
        echo ${{ secrets.HEROKU_API_KEY }} | heroku auth:token
        HEROKU_API_KEY=${{ secrets.HEROKU_API_KEY }} heroku container:login
#        docker login --username=_ --password=${{ secrets.HEROKU_API_KEY }} registry.heroku.com
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

    - name: Build and push Docker image
      run: |
        cd backend
        docker build --no-cache -t registry.heroku.com/osecours-api/web .
        docker push registry.heroku.com/${{ secrets.HEROKU_APP_API_NAME }}/web

    - name: Deploy to Heroku
      run: |
        heroku container:release web --app ${{ secrets.HEROKU_APP_API_NAME }}
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_API_NAME }}